version: '3.7'

services:
  #  app:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bloom
  #    depends_on:
  #      - db-dev
  db-dev:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: bloom
      POSTGRES_DB: bloom
    volumes:
      - db_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_dev_data: