spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bloom
    username: bloom
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
jwt:
  secret-key: "supersecretjwtkeysupersecretjwtkeysupersecretjwtkeysupersecretjwtkey"
  expiration-time: 500
  refresh-key: "supersecretrefreshkeysupersecretrefreshkeysupersecretrefresh"
  refresh-expiration-time: 2592000
cloudinary:
  name: dflmm6nmr
  apiKey: 368562557716915
  apiSecret: Es2b1xtKNJ0oI61Tv6iB7Qp9I2c