spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bloom
    username: bloom
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
jwt:
  secret-key: "supersecretjwtkeysupersecretjwtkeysupersecretjwtkeysupersecretjwtkey"
  expiration-time: 900000